import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export interface Topics {
  id: number;
  title: string;
  body: string;
}
// import "./reset.css";

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by YoonKyeongmin",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch(`${process.env.NEXT_PUBLIC_API_URL}` + "topics", {
    cache: "no-store",
  });
  const topics: Topics[] = await resp.json();

  return (
    <html>
      <body>
        <nav>
          <h1>
            <Link href={"/"}>WEB</Link>
          </h1>
          <ol>
            {topics.map((topic) => {
              return (
                <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                </li>
              );
            })}
          </ol>
        </nav>
        <main>{children}</main>
        <Control></Control>
      </body>
    </html>
  );
}
