import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

interface Topics {
  id: number;
  title: string;
  body: string;
}
// import "./reset.css";

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by YoonKyeongmin",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch("http://localhost:9999/topics");
  const topics: Topics[] = await resp.json();

  return (
    <html>
      <body>
        <nav>
          <h1>
            <Link href={"/"}>WEB</Link>
          </h1>
          <ol>
            {topics.map((topic) => {
              return (
                <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                </li>
              );
            })}
          </ol>
        </nav>
        <main>{children}</main>
        <footer>
          <ul>
            <li>
              <Link href="/create">Create</Link>
            </li>
            <li>
              <Link href="/update/1">Update</Link>
            </li>
            <li>
              <button type="button">delete</button>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
